<?php

declare(strict_types=1);

/**
 * @var \LizardsAndPumpkins\Import\TemplateRendering\Block $this
 */
?>
<div class="newsletter-fullsize">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-md-5 col-sm-6 col-xs-6">
                <div class="text-front">Newsletter</div>
                <form class="form-inline form-block-3-button margin-left-2" method="post" action="/" data-plenty="submit:Validator.validate(this, 'has-error')">
                    <input name="ActionCall" value="WebActionSendCmsForm" type="hidden">
                    <input name="FormID" value="-1" type="hidden">
                    <input name="EMailDirID" value="6" type="hidden">
                    <input name="BranchId" value="37" type="hidden">
                    <label class="sr-only" for="newsletterEmail">E-Mail-Adresse</label>
                    <input class="form-control" id="newsletterEmail" name="FormFields[2]" placeholder="E-Mail-Adresse" data-plenty-validate="mail" type="email">
                    <button class="btn btn-primary onlyIcon" type="submit">
                        <span>»</span>
                    </button>
                </form>
            </div>
            <div class="col-lg-7 col-md-7 col-sm-6 col-xs-6 uppercase fs15" style="line-height:normal;">
                <div>Kostenlos von Rabatt-Aktionen erfahren!**</div>
            </div>
        </div>
    </div>
</div>
<footer>

    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <a href="/">
                    <img src="https://www.outlet46.de/layout/outlet46-reboot/img/outlet46-logo.png" alt="Outlet46.de" class="img-responsive" height="77" width="286">
                </a>
                <p class="margin-top-2">
                    Der Mode Online-Shop bietet Markenschuhe günstig für Damen und Herren in einer großen Auswahl an.
                    Da zur Vollendung des persönlichen Outfits auch die passende Kleidung gehört, gibt es
                    im Online-Outlet auch gleich noch preiswerte Kleidung zu kaufen...
                </p>
                <div class="tel-box margin-top-2">
                    <div>Beratung &amp; Bestellung</div>
                    <div>05321 - 3896690</div>
                </div>
                <p class="margin-top-25 clearfix">
                    <a class="icon-facebook-squared fs36 green pull-left" href="https://www.facebook.com/Outlet46" data-toggle="tooltip" data-placement="top" data-original-title="Like uns bei Facebook" target="_blank"></a>
                    <a class="icon-twitter-squared fs36 green margin-left-minus-10 pull-left" href="https://twitter.com/Outlet46_de" data-toggle="tooltip" data-placement="top" data-original-title="Folge uns auf Twitter" target="_blank"></a>
                    <a class="icon-instagram fs36 green margin-left-minus-10 pull-left" href="https://instagram.com/outlet46.de/" data-toggle="tooltip" data-placement="top" data-original-title="Besuche uns auf Instagram" target="_blank"></a>
                    <a class="icon-youtube-squared fs36 green margin-left-minus-10 pull-left" href="//www.youtube.com/channel/UCY7Tl5TqZdlu7VBIDLynBUg" data-toggle="tooltip" data-placement="top" data-original-title="Besuche uns auf YouTube" target="_blank"></a>
                    <a class="fs36 margin-top-025 pull-left margin-left-1" href="https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=857690011&amp;mt=8" target="_blank">
                        <img src="https://www.outlet46.de/layout/outlet46-reboot/img/apple-store-app.jpg" data-toggle="tooltip" data-placement="top" data-original-title="Unsere App im Appstore" height="31" width="89">
                    </a>
                    <a class="fs36 margin-top-025 pull-left margin-left-1" href="https://play.google.com/store/apps/details?id=com.shopgate.android.app10159" target="_blank">
                        <img src="https://www.outlet46.de/layout/outlet46-reboot/img/googleplay-store-app.jpg" data-toggle="tooltip" data-placement="top" data-original-title="Unsere App im Google Playstore" height="31" width="89">
                    </a>
                </p>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-xs-offset-1 col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        <p class="h4 uppercase">Informationen</p>
                        <ul class="uppercase">
                            <li><a href="https://www.outlet46.de/content/unternehmen/">Über Uns</a></li>
                            <li><a href="https://www.outlet46.de/content/ihre-vorteile/">Ihre Vorteile</a></li>
                            <li><a href="https://www.outlet46.de/content/newsletter/">Newsletter</a></li>
                            <li><a href="https://www.outlet46.de/content/partnerprogramme/">Partnerprogramm</a></li>
                            <li><a href="https://www.outlet46.de/content/lieferant-werden/">Lieferant werden</a></li>
                            <li><a href="https://www.outlet46.de/content/originalitaet/">Originalware</a></li>
                            <li><a href="https://www.outlet46.de/content/presse/">Presse</a></li>
                            <li><a href="https://www.outlet46.de/content/widerrufsbelehrung/">Widerruf</a></li>
                            <li><a href="https://www.outlet46.de/content/agb/">AGB</a></li>
                            <li><a href="https://www.outlet46.de/content/datenschutz/">Datenschutz</a></li>
                            <li><a href="https://www.outlet46.de/content/schuhe-online-guenstig-kaufen/">Impressum</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        <p class="h4 uppercase">Service</p>
                        <ul class="uppercase">
                            <li><a href="https://www.outlet46.de/outlet46/kontakt/">Kontakt</a></li>
                            <li><a href="https://www.outlet46.de/outlet46/versandkosten/">Zahlung &amp; Versand</a></li>
                            <li><a href="https://www.outlet46.de/content/ruecksendungen/">Rücksendungen</a></li>
                            <li><a href="https://www.outlet46.de/outlet46/faq/">Hilfe / FAQ</a></li>
                        </ul>
                        <ul class="margin-top-2">
                            <li>
                                <a href="https://www.outlet46.de/outlet46/versandkosten/">
                                    <img src="https://www.outlet46.de/images/gallery/outlet46/zahlungsarten-footer.png" alt="Unsere Zahlarten" title="Unsere Zahlarten" height="110" width="185">
                                </a>
                            </li>
                            <li>

                            </li>
                            <li>
                                <a href="https://www.outlet46.de/outlet46/versandkosten/">
                                    <img src="https://www.outlet46.de/images/gallery/outlet46/dhl-sw.png" alt="Unser Versanddienstleister" title="Unser Versanddienstleister" height="35" width="87">
                                </a>
                            </li>
                        </ul>



                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                        <p class="h4 uppercase">Sicherheit</p>
                        <ul>
                            <li>
                                <div class="img-responsive-container">
                                    <div id="shopauskunft_widget" class="margin-bottom-1">
                                        <a href="https://www.shopauskunft.de/review/www.outlet46.de" target="_blank">
                                            <img src="<?= $this->getBaseUrl() ?>css/shopauskunft.png" alt="ShopAuskunft.de Siegel" height="213" width="180" border="0">
                                        </a>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                        <a href="https://www.outlet46.de/content/originalitaet/" target="_blank">
                                            <img src="https://www.outlet46.de/images/gallery/outlet46/kaeuferschutz-footer.png" alt="Händlerbung Käufersiegel" title="" data-toggle="tooltip" data-placement="top" data-original-title="Händlerbund Käufersiegel">
                                        </a>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                        <a class="margin-left-1" href="https://www.trustedshops.de/bewertung/info_X565A854FCC77FDF642A414DA7D104633.html" target="_blank"><img src="https://www.outlet46.de/images/gallery/outlet46/trusted-shops-footer.png" title="Trusetd Shops" alt="Trusetd Shops" hspace="0" vspace="0" border="0"></a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="container margin-top-2">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 text-left">
                Alle Preise inkl. gesetzlicher MwSt. * Unverbindliche Preisempfehlung des Herstellers. ** Abmeldung jederzeit möglich.
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 text-right">
                &copy; 2017 Outlet46 | Design by <a href="http://www.purpure.de" target="_blank">purpure</a>
            </div>
        </div>
    </div>
</footer>
<!--
<footer>
    <div class="footer-newsletter">
        <p class="subscribe-title">
            <?= $this->__('Subscribe to our newsletter <span>and you\'ll get 5% discount on your next order</span>') ?>
        </p>
        <form action="<?= $this->getBaseUrl() ?>newsletter/subscriber/new/" method="post" class="span_6" id="newsletter-validate-detail">
            <input type="text" name="email" id="newsletter" placeholder="<?= $this->__('Your email address') ?>" />
            <button type="submit" class="button normal"><?= $this->__('Subscribe') ?></button>
        </form>
    </div>
    <div class="footer-trust clearfix">
        <div class="col span_6">
            <p class="trust-title"><?= $this->__('Secure payment<br>with SSL encryption') ?></p>
            <p><img src="<?= $this->getBaseUrl() ?>images/payment-icons.jpg" alt="" class="payment-icons" /></p>
        </div>
        <div class="col span_6">
            <p class="trust-title"><?= $this->__('Do your have questions?<br>Please contat us!') ?></p>
            <p><a href="tel:+49112233445566">+49(0)112233445566</a></p>
        </div>
    </div>

    <div class="footer-wrapper clearfix">
        <div class="footer-category">
            <p class="title">Support</p>
            <p class="link"><a href="<?= $this->getBaseUrl() ?>">Shipping</a></p>
            <p class="link"><a href="#">Payment</a></p>
            <p class="link"><a href="#">Revocation</a></p>
            <p class="link"><a href="#">Contact</a></p>
        </div>

        <div class="footer-category">
            <p class="title">Legals</p>
            <p class="link"><a href="#">Terms</a></p>
            <p class="link"><a href="#">Privacy</a></p>
            <p class="link"><a href="#">Imprint</a></p>
        </div>

        <div class="footer-category">
            <p class="title">Company</p>
            <p class="link"><a href="#">About us</a></p>
            <p class="link"><a href="#">Stores</a></p>
            <p class="link"><a href="#">Joby</a></p>
            <p class="link"><a href="#">Team</a></p>
        </div>

        <div class="footer-category">
            <p class="title">Social</p>
            <p class="link">
                <a href="https://www.facebook.com" title="LP @ Facebook" target="_blank">
                    <svg class="icon facebook" viewBox="0 0 1024 1024">
                        <use xlink:href="<?= $this->getBaseUrl() ?>images/assets.svg#facebook"></use>
                    </svg>
                </a>
            </p>
            <p class="link">
                <a href="https://twitter.com" title="LP @ Twitter" target="_blank">
                    <svg class="icon twitter" viewBox="0 0 1024 1024">
                        <use xlink:href="<?= $this->getBaseUrl() ?>images/assets.svg#twitter"></use>
                    </svg>
                </a>
            </p>
            <p class="link">
                <a href="https://www.youtube.com" title="LP @ Youtube" target="_blank">
                    <svg class="icon youtube" viewBox="0 0 1024 1024">
                        <use xlink:href="<?= $this->getBaseUrl() ?>images/assets.svg#youtube"></use>
                    </svg>
                </a>
            </p>
        </div>
    </div>
</footer>
-->
