<?php

declare(strict_types=1);

/**
 * @var \LizardsAndPumpkins\Import\TemplateRendering\Block $this
 */
?>
<head>
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <title>
        <?= $this->getChildOutput('title') ?>
    </title>

    <link rel="stylesheet" type="text/css" href="https://www.outlet46.de/tpl/de/layout/outlet46_ppp/outlet46_ppp_de_content.css" />
    <link rel="shortcut icon" type="image/ico" href="https://www.outlet46.de/tpl/favicon_0.ico" />
    <meta name="robots" content="ALL" />
    <meta charset="utf-8">
    <style>
        .isLogin,
        .isMyaccount { min-width:120px; }
    </style>
    <script data-main="<?= $this->getBaseUrl() ?>js/<?= $this->getLayoutHandle() ?>" src="<?= $this->getBaseUrl() ?>js/lib/require.js"></script>
    <link type="text/css" rel="stylesheet" href="<?= $this->getBaseUrl() ?>css/<?= $this->getLayoutHandle() ?>.css" />
</head>
{{snippet head_container}}
