<?php

declare(strict_types = 1);

/**
 * @var \LizardsAndPumpkins\Import\TemplateRendering\Block $this
 */

$currentWebsiteCode = $this->getWebsiteCode();

?>
<nav class="navbar navbar-default nav-main" role="navigation" data-plenty="nav">
    <div class="nav-main-container">
        <!-- contact, informations, login, cart -->
        <div class="container relative">
            <div class="navbar-information clearfix">
                <ul class="nav navbar-nav navbar-right ">
                    <li class="isTextonly uppercase">
                        <span class="bold">Versandkostenfrei</span> in DE
                    </li>
                    <li class="isPhone uppercase">
                        Beratung &amp; Bestellung <a class="bold" href="tel: 05321 - 3896690">05321 - 3896690</a>
                    </li>

                    <li class="dropdown isLogin enable-xs-sm"><a href="javascript:void(0);"
                                                                 class="dropdown-toggle uppercase"
                                                                 data-plenty-enable="toggle-xs-sm-or-touch"> Mein
                            Konto</a>
                        <ul class="dropdown-menu dropdown-menu-right dropdown-padding" role="menu"
                            data-plenty="loginFormContainer">
                            <li>
                                <form class="loginForm plentyCheckForm" action="https://www.outlet46.de/"
                                      enctype="multipart/form-data" method="post" name="plenty_form"
                                      data-plenty-checkform="has-error"><input name="ActionCall"
                                                                               value="WebActionOrderLogin"
                                                                               type="hidden"> <input
                                        name="AccountShowNext" value="MyAccount" type="hidden"> <input
                                        name="AccountShow" value="MyAccount" type="hidden"> <input class="formblanc"
                                                                                                   name="already_customer"
                                                                                                   value="1"
                                                                                                   type="hidden">
                                    <div class="clearfix"><input class="form-control plentyRequired" name="email"
                                                                 placeholder="E-Mail" data-plenty-validate="mail"
                                                                 type="text"> <input class="form-control plentyRequired"
                                                                                     name="pwd" placeholder="Passwort"
                                                                                     data-plenty-validate="text"
                                                                                     type="password">
                                        <button class="btn btn-primary onlyIcon" type="submit"><span
                                                class="large glyphicon glyphicon-arrow-right"></span></button>
                                    </div>
                                    <div class="margin-top-05"><a class="iconLink" href="/?OrderShow=LostPWD"><span
                                                class="glyphicon glyphicon-question-sign"></span>&nbsp;Passwort
                                            vergessen?</a></div>
                                    <hr class="margin-top-05 margin-bottom-05">
                                    <div class="clearfix"><a class="iconLink pull-left"
                                                             href="https://www.outlet46.de/bestellprozess/registrierung/"><span
                                                class="glyphicon glyphicon-pencil"></span>&nbsp;Registrieren</a> <a
                                            class="iconLink cancel pull-right" href="javascript:void(0);"
                                            data-plenty="cancelLogin"><span class="glyphicon glyphicon-remove"></span>&nbsp;Abbrechen</a>
                                    </div>
                                </form>
                            </li>
                        </ul>
                    </li>

                    <li class="isTextonly uppercase">
                        <a href="https://www.outlet46.de/-AccountShowQQWatchlist/">Merkliste</a>
                    </li>

                </ul>
                <ul class="nav navbar-nav second">
                    <li class="isSearch">
                        <form class="navbar-right navbar-form content_search_form" role="search" name="search_form"
                              action="<?= $this->getBaseUrl() ?>catalogsearch/result/" method="get">
                            <div class="form-group navbarInputWrapper">
                                <input name="ActionCall" value="WebActionArticleSearch" type="hidden">
                                <input id="LiveSearchParam" class="form-control" autocomplete="off" name="q"
                                       placeholder="Suchen" type="search">
                            </div>
                            <button class="btn-search onlyIcon transition" type="submit">
                                <span class="glyphicon glyphicon-search"></span>
                                <span class="sr-only">Finden</span>
                            </button>
                            <div id="livesearch_result" class="liveSearch"></div>
                        </form>
                    </li>
                    <li class="dropdown isBasketPreview">
                        <a href="https://www.outlet46.de/bestellprozess/warenkorb/" class="dropdown-toggle"
                           data-plenty-enable="toggle-xs-sm-or-touch"
                           data-plenty-openremotetab="[data-plenty-tab-id=basketpreview]">
                            <span class="BasketIcon"><span class="icon-bag"></span></span><span class="BasketTotal">Einkaufstasche <span
                                    class="restBasketTotal">19,99</span> €</span>
                        </a>
                        <ul class="dropdown-menu dropdown-padding" role="menu">
                            <li>
                                <div class="overlay aside-overlay closeIcon top-left"
                                     data-plenty-toggle="{ target: 'body', class: 'aside-visible' }"></div>
                                <div class="basketPreviewContainer asidePanel" data-plenty="basketPreviewContainer">
                                    <div data-plenty-remotetabs-id="aside"
                                         data-plenty-tabpanel-labelledby="basketpreview">
                                        <div id="basket_preview_container"
                                             class="basketPreviewContent gradient-y-fade-in">

                                        </div>
                                        <div class="basketPreviewAltMessage">Sie haben noch keine Artikel im
                                            Warenkorb.
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div class="container relative">
            <!-- mobile navbar -->
            <div class="navbar-header">
                <a href="https://www.outlet46.de/content/auszeichnungen/" class="topshop hidden-xs hidden-sm">
                    <img src="https://www.outlet46.de/images/gallery/outlet46/outlet46-computerbild-topshop2015.png"
                         height="73" width="52">
                </a>
                <div class="navbar-brand">
                    <a href="/"><img src="https://www.outlet46.de/layout/outlet46-reboot/img/outlet46-logo.png"
                                     alt="Outlet46.de" height="77" width="286"></a>
                </div>
            </div>
        </div>
        <div class="darkbg">
            <div class="container relative">
                <!-- search, main navbar -->
                <div class="mainNavigation clearfix" data-plenty="mainNavigation">


                    <ul class="nav navbar-nav navbar-main" data-plenty="navbar-main">

                        <li class="cat-52 dropdown hasSublevel">
                            <a href="<?= $this->getBaseUrl() ?>/Herrenschuhe/"
                               data-plenty-enable="toggle-xs-sm-or-touch">
                                Herrenschuhe
                            </a>

                        </li>


                        <li class="cat-44 dropdown hasSublevel">
                            <a href="<?= $this->getBaseUrl() ?>/Damenschuhe/" data-plenty-enable="toggle-xs-sm-or-touch">
                                Damenschuhe
                            </a>
                        </li>


                        <li class="cat-36 dropdown hasSublevel active">
                            <a href="<?= $this->getBaseUrl() ?>/Herrenbekleidung/"
                               data-plenty-enable="toggle-xs-sm-or-touch">
                                Herrenbekleidung
                            </a>
                        </li>


                        <li class="cat-35 dropdown hasSublevel">
                            <a href="<?= $this->getBaseUrl() ?>/Damenbekleidung/"
                               data-plenty-enable="toggle-xs-sm-or-touch">
                                Damenbekleidung
                            </a>
                        </li>


                        <li class="cat-81 dropdown hasSublevel">
                            <a href="<?= $this->getBaseUrl() ?>/Kinder/" data-plenty-enable="toggle-xs-sm-or-touch">
                                Kinder
                            </a>
                        </li>


                        <li class="cat-80 dropdown hasSublevel">
                            <a href="<?= $this->getBaseUrl() ?>/Sport/" data-plenty-enable="toggle-xs-sm-or-touch">
                                Sport
                            </a>
                        </li>
                        <li class="cat-78 dropdown hasSublevel">
                            <a href="<?= $this->getBaseUrl() ?>/Accessoires/"
                               data-plenty-enable="toggle-xs-sm-or-touch">
                                Accessoires
                            </a>
                        </li>


                        <li class="cat-60 dropdown hasSublevel bigmenu">
                            <a href="<?= $this->getBaseUrl() ?>/Marken/"
                               data-plenty-enable="toggle-xs-sm-or-touch">
                                Marken
                            </a>

                        </li>
                    </ul>
                </div>
                <div class="overlay navigation-overlay closeIcon top-right"
                     data-plenty-toggle="{ target: 'body', class: 'navigation-visible' }"></div>
            </div>
        </div>

    </div>
</nav>

<!--
<header>
    <div class="language-wrapper">
        <div class="language-switch">
            <p><?= $this->__('Please, chose your language') ?></p>

            <a class="lang-flag" href="<?= preg_replace('#[^/]+/?$#', 'de/', $this->getBaseUrl()) ?>">
                <img src="<?= $this->getBaseUrl() ?>images/flags/de.png" alt=""/>
                <span>Deutsch</span>
            </a>
            <a class="lang-flag" href="<?= preg_replace('#[^/]+/?$#', 'en/', $this->getBaseUrl()) ?>">
                <img src="<?= $this->getBaseUrl() ?>images/flags/en.png" alt=""/>
                <span>English</span>
            </a>
            <a class="lang-flag" href="<?= preg_replace('#[^/]+/?$#', 'fr/', $this->getBaseUrl()) ?>">
                <img src="<?= $this->getBaseUrl() ?>images/flags/fr.png" alt=""/>
                <span>Français</span>
            </a>

            <i class="language-switch-close"></i>
        </div>
    </div>

    <div class="header-wrapper clearfix">

        <div id="mobile-menu">
            <span class="lines"></span>
        </div>

        <a href="<?= $this->getBaseUrl() ?>"
           title="<?= $this->__(' - Lizards & Pumpkins') ?>"
           class="logo" >
            <svg class="icon main-logo" viewBox="0 0 1024 1024">
                <use xlink:href="<?= $this->getBaseUrl() ?>images/assets.svg#main-logo"></use>
            </svg>
            <svg class="icon mobile-logo" viewBox="0 0 1024 1024">
                <use xlink:href="<?= $this->getBaseUrl() ?>images/assets.svg#mobile-logo"></use>
            </svg>
        </a>

        <i id="mobile-search">
            <svg class="icon magnifier" viewBox="0 0 1024 1024">
                <use xlink:href="<?= $this->getBaseUrl() ?>images/assets.svg#magnifier"></use>
            </svg>
        </i>

        <ul class="top-links">
            <li id="account-meta"></li>
            <li id="language-switcher">
                <img src="<?= $this->getBaseUrl() ?>images/flags/<?= $currentWebsiteCode ?>.png" alt=""/>
            </li>
            <li>
                <a href="<?= $this->getBaseUrl() ?>checkout/cart/">
                    <svg class="icon-shopping-bag" viewBox="0 0 1024 1024">
                        <use xlink:href="<?= $this->getBaseUrl() ?>images/assets.svg#shopping-bag"></use>
                    </svg>
                    <span id="cart-meta-info"></span>
                </a>
            </li>
        </ul>

        <form id="search_mini_form" action="<?= $this->getBaseUrl() ?>catalogsearch/result/" method="get" autocomplete="off">
            <fieldset>
                <div class="form-search">
                    <input id="search" type="text" name="q"
                           placeholder="<?= $this->__('What are you looking for?') ?>"
                           autocomplete="off" />

                    <button type="submit" title="<?= $this->__('Search') ?>">
                        <svg class="icon magnifier" viewBox="0 0 1024 1024">
                            <use xlink:href="<?= $this->getBaseUrl() ?>images/assets.svg#magnifier"></use>
                        </svg>
                    </button>

                    <div id="search-autosuggestion"></div>
                </div>
            </fieldset>
        </form>
    </div>

    <?= $this->getChildOutput('content_block_main-menu') ?>
</header>-->
