<?php

declare(strict_types = 1);

/**
 * @var \LizardsAndPumpkins\Import\TemplateRendering\Block $this
 */

$currentWebsiteCode = $this->getWebsiteCode();

?>
<nav class="navbar navbar-default nav-main" role="navigation" data-plenty="nav">
    <div class="nav-main-container">
        <!-- contact, informations, login, cart -->
        <div class="container relative">
            <div class="navbar-information clearfix">
                <ul class="nav navbar-nav navbar-right ">
                    <li class="isTextonly uppercase">
                        <span class="bold">Versandkostenfrei</span> in DE
                    </li>
                    <li class="isPhone uppercase">
                        Beratung &amp; Bestellung <a class="bold" href="tel: 05321 - 3896690">05321 - 3896690</a>
                    </li>

                    <li class="dropdown isLogin enable-xs-sm"><a href="javascript:void(0);"
                                                                 class="dropdown-toggle uppercase"
                                                                 data-plenty-enable="toggle-xs-sm-or-touch"> Mein
                            Konto</a>
                        <ul class="dropdown-menu dropdown-menu-right dropdown-padding" role="menu"
                            data-plenty="loginFormContainer">
                            <li>
                                <form class="loginForm plentyCheckForm" action="https://www.outlet46.de/"
                                      enctype="multipart/form-data" method="post" name="plenty_form"
                                      data-plenty-checkform="has-error"><input name="ActionCall"
                                                                               value="WebActionOrderLogin"
                                                                               type="hidden"> <input
                                        name="AccountShowNext" value="MyAccount" type="hidden"> <input
                                        name="AccountShow" value="MyAccount" type="hidden"> <input class="formblanc"
                                                                                                   name="already_customer"
                                                                                                   value="1"
                                                                                                   type="hidden">
                                    <div class="clearfix"><input class="form-control plentyRequired" name="email"
                                                                 placeholder="E-Mail" data-plenty-validate="mail"
                                                                 type="text"> <input class="form-control plentyRequired"
                                                                                     name="pwd" placeholder="Passwort"
                                                                                     data-plenty-validate="text"
                                                                                     type="password">
                                        <button class="btn btn-primary onlyIcon" type="submit"><span
                                                class="large glyphicon glyphicon-arrow-right"></span></button>
                                    </div>
                                    <div class="margin-top-05"><a class="iconLink" href="/?OrderShow=LostPWD"><span
                                                class="glyphicon glyphicon-question-sign"></span>&nbsp;Passwort
                                            vergessen?</a></div>
                                    <hr class="margin-top-05 margin-bottom-05">
                                    <div class="clearfix"><a class="iconLink pull-left"
                                                             href="https://www.outlet46.de/bestellprozess/registrierung/"><span
                                                class="glyphicon glyphicon-pencil"></span>&nbsp;Registrieren</a> <a
                                            class="iconLink cancel pull-right" href="javascript:void(0);"
                                            data-plenty="cancelLogin"><span class="glyphicon glyphicon-remove"></span>&nbsp;Abbrechen</a>
                                    </div>
                                </form>
                            </li>
                        </ul>
                    </li>

                    <li class="isTextonly uppercase">
                        <a href="https://www.outlet46.de/-AccountShowQQWatchlist/">Merkliste</a>
                    </li>

                </ul>
                <ul class="nav navbar-nav second">
                    <li class="isSearch">
                        <form class="navbar-right navbar-form content_search_form" role="search" name="search_form"
                              action="<?= $this->getBaseUrl() ?>catalogsearch/result/" method="get">
                            <div class="form-group navbarInputWrapper">
                                <input name="ActionCall" value="WebActionArticleSearch" type="hidden">
                                <input id="LiveSearchParam" class="form-control" autocomplete="off" name="q"
                                       placeholder="Suchen" type="search">
                            </div>
                            <button class="btn-search onlyIcon transition" type="submit">
                                <span class="glyphicon glyphicon-search"></span>
                                <span class="sr-only">Finden</span>
                            </button>
                            <div id="livesearch_result" class="liveSearch"></div>
                        </form>
                    </li>
                    <li class="dropdown isBasketPreview">
                        <a href="https://www.outlet46.de/bestellprozess/warenkorb/" class="dropdown-toggle"
                           data-plenty-enable="toggle-xs-sm-or-touch"
                           data-plenty-openremotetab="[data-plenty-tab-id=basketpreview]">
                            <span class="BasketIcon"><span class="icon-bag"></span></span><span class="BasketTotal">Einkaufstasche <span
                                    class="restBasketTotal">19,99</span> €</span>
                        </a>
                        <ul class="dropdown-menu dropdown-padding" role="menu">
                            <li>
                                <div class="overlay aside-overlay closeIcon top-left"
                                     data-plenty-toggle="{ target: 'body', class: 'aside-visible' }"></div>
                                <div class="basketPreviewContainer asidePanel" data-plenty="basketPreviewContainer">
                                    <div data-plenty-remotetabs-id="aside"
                                         data-plenty-tabpanel-labelledby="basketpreview">
                                        <div id="basket_preview_container"
                                             class="basketPreviewContent gradient-y-fade-in">

                                        </div>
                                        <div class="basketPreviewAltMessage">Sie haben noch keine Artikel im
                                            Warenkorb.
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div class="container relative">
            <!-- mobile navbar -->
            <div class="navbar-header">
                <a href="https://www.outlet46.de/content/auszeichnungen/" class="topshop hidden-xs hidden-sm">
                    <img src="https://www.outlet46.de/images/gallery/outlet46/outlet46-computerbild-topshop2015.png"
                         height="73" width="52">
                </a>
                <div class="navbar-brand">
                    <a href="/"><img src="https://www.outlet46.de/layout/outlet46-reboot/img/outlet46-logo.png"
                                     alt="Outlet46.de" height="77" width="286"></a>
                </div>
            </div>
        </div>
        <div class="darkbg">
            <div class="container relative">
                <!-- search, main navbar -->
                <div class="mainNavigation clearfix" data-plenty="mainNavigation">


                    <ul class="nav navbar-nav navbar-main" data-plenty="navbar-main">

                        <li class="cat-52 dropdown hasSublevel">
                            <a href="https://www.outlet46.de/herrenschuhe-guenstig-kaufen/"
                               data-plenty-enable="toggle-xs-sm-or-touch">
                                Herrenschuhe
                            </a>


                            <ul class="dropdown-menu" data-plenty="navbar-main">

                                <li class="cat-53">
                                    <a href="https://www.outlet46.de/herrenschuhe-guenstig-kaufen/sneaker-guenstig-im-outlet/">
                                        Turnschuhe &amp; Sneaker
                                    </a>

                                </li>


                                <li class="cat-56">
                                    <a href="https://www.outlet46.de/herrenschuhe-guenstig-kaufen/trekkingschuhe-wanderschuhe/">
                                        Trekkingschuhe &amp; Wanderschuhe
                                    </a>

                                </li>


                                <li class="cat-55">
                                    <a href="https://www.outlet46.de/herrenschuhe-guenstig-kaufen/stiefel-boots/">
                                        Stiefel &amp; Boots
                                    </a>

                                </li>


                                <li class="cat-54">
                                    <a href="https://www.outlet46.de/herrenschuhe-guenstig-kaufen/schnuerschuhe-halbschuhe/">
                                        Schnürschuhe &amp; Halbschuhe
                                    </a>

                                </li>


                                <li class="cat-325">
                                    <a href="https://www.outlet46.de/herrenschuhe-guenstig-kaufen/hausschuhe-pantoffeln/">
                                        Hausschuhe &amp; Pantoffeln
                                    </a>

                                </li>


                                <li class="cat-58">
                                    <a href="https://www.outlet46.de/herrenschuhe-guenstig-kaufen/sandalen-zehentrenner/">
                                        Sandalen &amp; Zehentrenner
                                    </a>

                                </li>


                                <li class="cat-59">
                                    <a href="https://www.outlet46.de/herrenschuhe-guenstig-kaufen/segelschuhe-bootsschuhe/">
                                        Segelschuhe &amp; Bootsschuhe
                                    </a>

                                </li>


                                <li class="cat-57">
                                    <a href="https://www.outlet46.de/herrenschuhe-guenstig-kaufen/slipper-mokassins/">
                                        Slipper &amp; Mokassins
                                    </a>

                                </li>

                            </ul>


                        </li>


                        <li class="cat-44 dropdown hasSublevel">
                            <a href="https://www.outlet46.de/damen-schuhe/" data-plenty-enable="toggle-xs-sm-or-touch">
                                Damenschuhe
                            </a>


                            <ul class="dropdown-menu" data-plenty="navbar-main">

                                <li class="cat-45">
                                    <a href="https://www.outlet46.de/damen-schuhe/sneaker-turnschuhe/">
                                        Sneaker &amp; Turnschuhe
                                    </a>

                                </li>


                                <li class="cat-49">
                                    <a href="https://www.outlet46.de/damen-schuhe/boots-stiefel/">
                                        Boots &amp; Stiefel
                                    </a>

                                </li>


                                <li class="cat-48">
                                    <a href="https://www.outlet46.de/damen-schuhe/halbschuhe-pumps/">
                                        Halbschuhe &amp; Pumps
                                    </a>

                                </li>


                                <li class="cat-326">
                                    <a href="https://www.outlet46.de/damen-schuhe/pantoffeln-hausschuhe/">
                                        Pantoffeln &amp; Hausschuhe
                                    </a>

                                </li>


                                <li class="cat-51">
                                    <a href="https://www.outlet46.de/damen-schuhe/zehentrenner-sandalen/">
                                        Zehentrenner &amp; Sandalen
                                    </a>

                                </li>


                                <li class="cat-50">
                                    <a href="https://www.outlet46.de/damen-schuhe/wanderschuhe-trekkingschuhe/">
                                        Wanderschuhe &amp; Trekkingschuhe
                                    </a>

                                </li>


                                <li class="cat-47">
                                    <a href="https://www.outlet46.de/damen-schuhe/ballerina-slipper/">
                                        Ballerina &amp; Slipper
                                    </a>

                                </li>


                                <li class="cat-46">
                                    <a href="https://www.outlet46.de/damen-schuhe/bootsschuhe-segelschuhe/">
                                        Bootsschuhe &amp; Segelschuhe
                                    </a>

                                </li>

                            </ul>


                        </li>


                        <li class="cat-36 dropdown hasSublevel active">
                            <a href="https://www.outlet46.de/herren-bekleidung/"
                               data-plenty-enable="toggle-xs-sm-or-touch">
                                Herrenbekleidung
                            </a>


                            <ul class="dropdown-menu" data-plenty="navbar-main">

                                <li class="cat-37 active">
                                    <a href="https://www.outlet46.de/herren-bekleidung/jeans-hosen/">
                                        Jeans &amp; Hosen
                                    </a>

                                </li>


                                <li class="cat-40">
                                    <a href="https://www.outlet46.de/herren-bekleidung/jacken-maentel/">
                                        Jacken &amp; Mäntel
                                    </a>

                                </li>


                                <li class="cat-42">
                                    <a href="https://www.outlet46.de/herren-bekleidung/unterwaesche-socken/">
                                        Unterwäsche &amp; Socken
                                    </a>

                                </li>


                                <li class="cat-38">
                                    <a href="https://www.outlet46.de/herren-bekleidung/pullover-sweater/">
                                        Pullover &amp; Sweater
                                    </a>

                                </li>


                                <li class="cat-39">
                                    <a href="https://www.outlet46.de/herren-bekleidung/t-shirts-tank-tops/">
                                        T-Shirts &amp; Tank Tops
                                    </a>

                                </li>


                                <li class="cat-41">
                                    <a href="https://www.outlet46.de/herren-bekleidung/hemden-poloshirts/">
                                        Hemden &amp; Poloshirts
                                    </a>

                                </li>


                                <li class="cat-43">
                                    <a href="https://www.outlet46.de/herren-bekleidung/shorts-bermudas/">
                                        Shorts &amp; Bermudas
                                    </a>

                                </li>


                                <li class="cat-308">
                                    <a href="https://www.outlet46.de/herren-bekleidung/nachtwaesche-bademode/">
                                        Nachtwäsche &amp; Bademode
                                    </a>

                                </li>


                                <li class="cat-280">
                                    <a href="https://www.outlet46.de/herren-bekleidung/jogginghosen-fitnessmode/">
                                        Jogginghosen &amp; Fitnessmode
                                    </a>

                                </li>

                            </ul>


                        </li>


                        <li class="cat-35 dropdown hasSublevel">
                            <a href="https://www.outlet46.de/damen-bekleidung/"
                               data-plenty-enable="toggle-xs-sm-or-touch">
                                Damenbekleidung
                            </a>


                            <ul class="dropdown-menu" data-plenty="navbar-main">

                                <li class="cat-87">
                                    <a href="https://www.outlet46.de/damen-bekleidung/hosen-jeans/">
                                        Hosen &amp; Jeans
                                    </a>

                                </li>


                                <li class="cat-495">
                                    <a href="https://www.outlet46.de/damen-bekleidung/tank-tops-t-shirts/">
                                        Tank Tops &amp; T-Shirts
                                    </a>

                                </li>


                                <li class="cat-568">
                                    <a href="https://www.outlet46.de/damen-bekleidung/poloshirts-blusen/">
                                        Poloshirts &amp; Blusen
                                    </a>

                                </li>


                                <li class="cat-89">
                                    <a href="https://www.outlet46.de/damen-bekleidung/sweater-pullover/">
                                        Sweater &amp; Pullover
                                    </a>

                                </li>


                                <li class="cat-88">
                                    <a href="https://www.outlet46.de/damen-bekleidung/maentel-jacken/">
                                        Mäntel &amp; Jacken
                                    </a>

                                </li>


                                <li class="cat-281">
                                    <a href="https://www.outlet46.de/damen-bekleidung/fitnessmode-jogginghosen/">
                                        Fitnessmode &amp; Jogginghosen
                                    </a>

                                </li>


                                <li class="cat-90">
                                    <a href="https://www.outlet46.de/damen-bekleidung/socken-unterwaesche/">
                                        Socken &amp; Unterwäsche
                                    </a>

                                </li>


                                <li class="cat-282">
                                    <a href="https://www.outlet46.de/damen-bekleidung/shorts-bermudas-roecke-kleider/">
                                        Shorts, Bermudas, Röcke &amp; Kleider
                                    </a>

                                </li>


                                <li class="cat-91">
                                    <a href="https://www.outlet46.de/damen-bekleidung/taschen/">
                                        Taschen
                                    </a>

                                </li>


                                <li class="cat-323">
                                    <a href="https://www.outlet46.de/damen-bekleidung/bademode-nachtwaesche/">
                                        Bademode &amp; Nachtwäsche
                                    </a>

                                </li>

                            </ul>


                        </li>


                        <li class="cat-81 dropdown hasSublevel">
                            <a href="https://www.outlet46.de/kinder/" data-plenty-enable="toggle-xs-sm-or-touch">
                                Kinder
                            </a>


                            <ul class="dropdown-menu" data-plenty="navbar-main">

                                <li class="cat-566">
                                    <a href="https://www.outlet46.de/kinder/hausschuhe/">
                                        Hausschuhe
                                    </a>

                                </li>


                                <li class="cat-93">
                                    <a href="https://www.outlet46.de/kinder/turnschuhe/">
                                        Turnschuhe
                                    </a>

                                </li>


                                <li class="cat-92">
                                    <a href="https://www.outlet46.de/kinder/halbschuhe/">
                                        Halbschuhe
                                    </a>

                                </li>


                                <li class="cat-94">
                                    <a href="https://www.outlet46.de/kinder/stiefel/">
                                        Stiefel
                                    </a>

                                </li>


                                <li class="cat-95">
                                    <a href="https://www.outlet46.de/kinder/sandale/">
                                        Sandale
                                    </a>

                                </li>


                                <li class="cat-291">
                                    <a href="https://www.outlet46.de/kinder/bekleidung/">
                                        Bekleidung
                                    </a>

                                </li>

                            </ul>


                        </li>


                        <li class="cat-80 dropdown hasSublevel">
                            <a href="https://www.outlet46.de/sport/" data-plenty-enable="toggle-xs-sm-or-touch">
                                Sport
                            </a>


                            <ul class="dropdown-menu" data-plenty="navbar-main">

                                <li class="cat-106">
                                    <a href="https://www.outlet46.de/sport/laufschuhe-joggingschuhe/">
                                        Laufschuhe &amp; Joggingschuhe
                                    </a>

                                </li>


                                <li class="cat-543">
                                    <a href="https://www.outlet46.de/sport/golfschuhe/">
                                        Golfschuhe
                                    </a>

                                </li>


                                <li class="cat-104">
                                    <a href="https://www.outlet46.de/sport/sportunterbekleidung/">
                                        Sportunterbekleidung
                                    </a>

                                </li>


                                <li class="cat-103">
                                    <a href="https://www.outlet46.de/sport/sportoberbekleidung/">
                                        Sportoberbekleidung
                                    </a>

                                </li>


                                <li class="cat-107">
                                    <a href="https://www.outlet46.de/sport/hallenschuhe/">
                                        Hallenschuhe
                                    </a>

                                </li>


                                <li class="cat-105">
                                    <a href="https://www.outlet46.de/sport/fussballschuhe/">
                                        Fußballschuhe
                                    </a>

                                </li>
                                <li class="cat-108">
                                    <a href="https://www.outlet46.de/sport/sporttaschen/">
                                        Sporttaschen
                                    </a>

                                </li>
                                <li class="cat-297">
                                    <a href="https://www.outlet46.de/sport/skijacke/">
                                        Skijacke
                                    </a>

                                </li>
                                <li class="cat-296">
                                    <a href="https://www.outlet46.de/sport/skihose/">
                                        Skihose
                                    </a>

                                </li>

                            </ul>

                        </li>
                        <li class="cat-78 dropdown hasSublevel">
                            <a href="https://www.outlet46.de/accessoires-guenstig/"
                               data-plenty-enable="toggle-xs-sm-or-touch">
                                Accessoires
                            </a>
                            <ul class="dropdown-menu" data-plenty="navbar-main">

                                <li class="cat-324">
                                    <a href="https://www.outlet46.de/accessoires-guenstig/rucksaecke-taschen/">
                                        Rucksäcke &amp; Taschen
                                    </a>

                                </li>


                                <li class="cat-100">
                                    <a href="https://www.outlet46.de/accessoires-guenstig/unterwaesche/">
                                        Unterwäsche
                                    </a>

                                </li>


                                <li class="cat-101">
                                    <a href="https://www.outlet46.de/accessoires-guenstig/struempfe-socken/">
                                        Strümpfe &amp; Socken
                                    </a>

                                </li>


                                <li class="cat-99">
                                    <a href="https://www.outlet46.de/accessoires-guenstig/guertel/">
                                        Gürtel
                                    </a>

                                </li>


                                <li class="cat-102">
                                    <a href="https://www.outlet46.de/accessoires-guenstig/caps-muetzen/">
                                        Caps &amp; Mützen
                                    </a>

                                </li>


                                <li class="cat-374">
                                    <a href="https://www.outlet46.de/accessoires-guenstig/portemonnaies/">
                                        Portemonnaies &amp; Geldbörsen
                                    </a>

                                </li>


                                <li class="cat-372">
                                    <a href="https://www.outlet46.de/accessoires-guenstig/handschuhe/">
                                        Handschuhe &amp; Schals
                                    </a>

                                </li>


                                <li class="cat-598">
                                    <a href="https://www.outlet46.de/accessoires-guenstig/damenduefte/">
                                        Damendüfte
                                    </a>

                                </li>


                                <li class="cat-599">
                                    <a href="https://www.outlet46.de/accessoires-guenstig/herrenduefte/">
                                        Herrendüfte
                                    </a>

                                </li>


                                <li class="cat-615">
                                    <a href="https://www.outlet46.de/accessoires-guenstig/damenuhren/">
                                        Damenuhren
                                    </a>

                                </li>


                                <li class="cat-616">
                                    <a href="https://www.outlet46.de/accessoires-guenstig/herrenuhren/">
                                        Herrenuhren
                                    </a>

                                </li>

                            </ul>


                        </li>


                        <li class="cat-60 dropdown hasSublevel bigmenu">
                            <a href="https://www.outlet46.de/marken-online-outlet/"
                               data-plenty-enable="toggle-xs-sm-or-touch">
                                Marken
                            </a>


                            <ul class="dropdown-menu" data-plenty="navbar-main">

                                <li class="cat-109">
                                    <a href="https://www.outlet46.de/marken-online-outlet/adidas-im-outlet/">
                                        adidas
                                    </a>

                                </li>


                                <li class="cat-587">
                                    <a href="https://www.outlet46.de/marken-online-outlet/airbus/">
                                        AIRBUS
                                    </a>

                                </li>


                                <li class="cat-549">
                                    <a href="https://www.outlet46.de/marken-online-outlet/aku/">
                                        AKU
                                    </a>

                                </li>


                                <li class="cat-344">
                                    <a href="https://www.outlet46.de/marken-online-outlet/arena-im-outlet/">
                                        arena
                                    </a>

                                </li>


                                <li class="cat-189">
                                    <a href="https://www.outlet46.de/marken-online-outlet/arqueonautas/">
                                        Arqueonautas
                                    </a>

                                </li>


                                <li class="cat-112">
                                    <a href="https://www.outlet46.de/marken-online-outlet/asics-im-outlet/">
                                        Asics
                                    </a>

                                </li>


                                <li class="cat-552">
                                    <a href="https://www.outlet46.de/marken-online-outlet/bally/">
                                        BALLY
                                    </a>

                                </li>


                                <li class="cat-591">
                                    <a href="https://www.outlet46.de/marken-online-outlet/bata-industrials/">
                                        Bata Industrials
                                    </a>

                                </li>


                                <li class="cat-592">
                                    <a href="https://www.outlet46.de/marken-online-outlet/bickz-by-bata-industrials/">
                                        Bickz by Bata Industrials
                                    </a>

                                </li>


                                <li class="cat-595">
                                    <a href="https://www.outlet46.de/marken-online-outlet/bio-life/">
                                        Bio life
                                    </a>

                                </li>


                                <li class="cat-410">
                                    <a href="https://www.outlet46.de/marken-online-outlet/boxfresh/">
                                        Boxfresh
                                    </a>

                                </li>


                                <li class="cat-217">
                                    <a href="https://www.outlet46.de/marken-online-outlet/brooks/">
                                        BROOKS
                                    </a>

                                </li>


                                <li class="cat-194">
                                    <a href="https://www.outlet46.de/marken-online-outlet/bruno-banani/">
                                        Bruno Banani
                                    </a>

                                </li>


                                <li class="cat-499">
                                    <a href="https://www.outlet46.de/marken-online-outlet/bruetting/">
                                        Brütting
                                    </a>

                                </li>


                                <li class="cat-186">
                                    <a href="https://www.outlet46.de/marken-online-outlet/buffalo/">
                                        Buffalo
                                    </a>

                                </li>


                                <li class="cat-216">
                                    <a href="https://www.outlet46.de/marken-online-outlet/calvin-klein/">
                                        Calvin Klein
                                    </a>

                                </li>


                                <li class="cat-570">
                                    <a href="https://www.outlet46.de/marken-online-outlet/camano/">
                                        camano
                                    </a>

                                </li>


                                <li class="cat-492">
                                    <a href="https://www.outlet46.de/marken-online-outlet/caprice/">
                                        CAPRICE
                                    </a>

                                </li>


                                <li class="cat-532">
                                    <a href="https://www.outlet46.de/marken-online-outlet/carhartt/">
                                        carhartt
                                    </a>

                                </li>


                                <li class="cat-617">
                                    <a href="https://www.outlet46.de/marken-online-outlet/casio/">
                                        CASIO
                                    </a>

                                </li>


                                <li class="cat-117">
                                    <a href="https://www.outlet46.de/marken-online-outlet/caterpillar-im-outlet/">
                                        CATERPILLAR
                                    </a>

                                </li>


                                <li class="cat-551">
                                    <a href="https://www.outlet46.de/marken-online-outlet/cayler-sons/">
                                        CAYLER &amp; SONS
                                    </a>

                                </li>


                                <li class="cat-185">
                                    <a href="https://www.outlet46.de/marken-online-outlet/cerruti-1881/">
                                        Cerruti 1881
                                    </a>

                                </li>


                                <li class="cat-600">
                                    <a href="https://www.outlet46.de/marken-online-outlet/chiemsee/">
                                        CHIEMSEE
                                    </a>

                                </li>


                                <li class="cat-118">
                                    <a href="https://www.outlet46.de/marken-online-outlet/cipo-baxx-im-outlet/">
                                        Cipo &amp; Baxx
                                    </a>

                                </li>


                                <li class="cat-199">
                                    <a href="https://www.outlet46.de/marken-online-outlet/clarks/">
                                        Clarks
                                    </a>

                                </li>


                                <li class="cat-606">
                                    <a href="https://www.outlet46.de/marken-online-outlet/collection-iceland/">
                                        Collection ICELAND
                                    </a>

                                </li>


                                <li class="cat-222">
                                    <a href="https://www.outlet46.de/marken-online-outlet/columbia/">
                                        Columbia
                                    </a>

                                </li>


                                <li class="cat-120">
                                    <a href="https://www.outlet46.de/marken-online-outlet/converse-im-outlet/">
                                        Converse
                                    </a>

                                </li>


                                <li class="cat-122">
                                    <a href="https://www.outlet46.de/marken-online-outlet/crocs-im-lagerverkauf/">
                                        Crocs
                                    </a>

                                </li>


                                <li class="cat-596">
                                    <a href="https://www.outlet46.de/marken-online-outlet/dakine/">
                                        DAKINE
                                    </a>

                                </li>


                                <li class="cat-124">
                                    <a href="https://www.outlet46.de/marken-online-outlet/diadora-im-outlet/">
                                        Diadora
                                    </a>

                                </li>


                                <li class="cat-193">
                                    <a href="https://www.outlet46.de/marken-online-outlet/dickies/">
                                        Dickies
                                    </a>

                                </li>


                                <li class="cat-125">
                                    <a href="https://www.outlet46.de/marken-online-outlet/diesel-im-outlet/">
                                        Diesel
                                    </a>

                                </li>


                                <li class="cat-192">
                                    <a href="https://www.outlet46.de/marken-online-outlet/dr-martens/">
                                        Dr. Martens
                                    </a>

                                </li>


                                <li class="cat-128">
                                    <a href="https://www.outlet46.de/marken-online-outlet/dsquared-im-outlet/">
                                        DSQUARED2
                                    </a>

                                </li>


                                <li class="cat-129">
                                    <a href="https://www.outlet46.de/marken-online-outlet/ecco-im-outlet/">
                                        ecco
                                    </a>

                                </li>


                                <li class="cat-618">
                                    <a href="https://www.outlet46.de/marken-online-outlet/emu-australia/">
                                        EMU Australia
                                    </a>

                                </li>


                                <li class="cat-605">
                                    <a href="https://www.outlet46.de/marken-online-outlet/ezano/">
                                        EZANO
                                    </a>

                                </li>


                                <li class="cat-494">
                                    <a href="https://www.outlet46.de/marken-online-outlet/fairplay/">
                                        FAIRPLAY
                                    </a>

                                </li>


                                <li class="cat-276">
                                    <a href="https://www.outlet46.de/marken-online-outlet/fred-perry/">
                                        FRED PERRY
                                    </a>

                                </li>


                                <li class="cat-474">
                                    <a href="https://www.outlet46.de/marken-online-outlet/gant/">
                                        GANT
                                    </a>

                                </li>


                                <li class="cat-475">
                                    <a href="https://www.outlet46.de/marken-online-outlet/geox/">
                                        GEOX
                                    </a>

                                </li>


                                <li class="cat-220">
                                    <a href="https://www.outlet46.de/marken-online-outlet/haflinger/">
                                        HAFLINGER
                                    </a>

                                </li>


                                <li class="cat-589">
                                    <a href="https://www.outlet46.de/marken-online-outlet/harrykson/">
                                        HARRYKSON
                                    </a>

                                </li>


                                <li class="cat-303">
                                    <a href="https://www.outlet46.de/marken-online-outlet/harvey-miller-polo-cub/">
                                        HARVEY MILLER POLO CLUB
                                    </a>

                                </li>


                                <li class="cat-594">
                                    <a href="https://www.outlet46.de/marken-online-outlet/hazard/">
                                        hazard
                                    </a>

                                </li>


                                <li class="cat-134">
                                    <a href="https://www.outlet46.de/marken-online-outlet/head-im-outlet/">
                                        Head
                                    </a>

                                </li>


                                <li class="cat-135">
                                    <a href="https://www.outlet46.de/marken-online-outlet/helly-hansen-im-outlet/">
                                        Helly Hansen
                                    </a>

                                </li>


                                <li class="cat-339">
                                    <a href="https://www.outlet46.de/marken-online-outlet/hunter-im-outlet/">
                                        HUNTER
                                    </a>

                                </li>


                                <li class="cat-611">
                                    <a href="https://www.outlet46.de/marken-online-outlet/integra-wear/">
                                        integra.wear
                                    </a>

                                </li>


                                <li class="cat-138">
                                    <a href="https://www.outlet46.de/marken-online-outlet/jack-jones-im-outlet/">
                                        Jack &amp; Jones
                                    </a>

                                </li>


                                <li class="cat-341">
                                    <a href="https://www.outlet46.de/marken-online-outlet/jack-wolfskin-im-outlet/">
                                        Jack Wolfskin
                                    </a>

                                </li>


                                <li class="cat-597">
                                    <a href="https://www.outlet46.de/marken-online-outlet/jolyne/">
                                        JOLYNE
                                    </a>

                                </li>


                                <li class="cat-610">
                                    <a href="https://www.outlet46.de/marken-online-outlet/joma/">
                                        joma
                                    </a>

                                </li>


                                <li class="cat-246">
                                    <a href="https://www.outlet46.de/marken-online-outlet/joop/">
                                        JOOP!
                                    </a>

                                </li>


                                <li class="cat-140">
                                    <a href="https://www.outlet46.de/marken-online-outlet/k-swiss-im-outlet/">
                                        K-Swiss
                                    </a>

                                </li>


                                <li class="cat-527">
                                    <a href="https://www.outlet46.de/marken-online-outlet/kamik/">
                                        kamik
                                    </a>

                                </li>


                                <li class="cat-224">
                                    <a href="https://www.outlet46.de/marken-online-outlet/kangaroos/">
                                        KangaROOS
                                    </a>

                                </li>


                                <li class="cat-141">
                                    <a href="https://www.outlet46.de/marken-online-outlet/kappa-im-lagerverkauf/">
                                        Kappa
                                    </a>

                                </li>


                                <li class="cat-412">
                                    <a href="https://www.outlet46.de/marken-online-outlet/karhu/">
                                        KARHU
                                    </a>

                                </li>


                                <li class="cat-473">
                                    <a href="https://www.outlet46.de/marken-online-outlet/keds/">
                                        Keds
                                    </a>

                                </li>


                                <li class="cat-612">
                                    <a href="https://www.outlet46.de/marken-online-outlet/killtec/">
                                        Killtec
                                    </a>

                                </li>


                                <li class="cat-619">
                                    <a href="https://www.outlet46.de/marken-online-outlet/kobbler-shoes/">
                                        Kobbler shoes
                                    </a>

                                </li>


                                <li class="cat-575">
                                    <a href="https://www.outlet46.de/marken-online-outlet/kodiak/">
                                        KODIAK
                                    </a>

                                </li>


                                <li class="cat-144">
                                    <a href="https://www.outlet46.de/marken-online-outlet/la-martina-im-outlet/">
                                        La Martina
                                    </a>

                                </li>


                                <li class="cat-145">
                                    <a href="https://www.outlet46.de/marken-online-outlet/lacoste-im-outlet/">
                                        Lacoste
                                    </a>

                                </li>


                                <li class="cat-263">
                                    <a href="https://www.outlet46.de/marken-online-outlet/le-chameau/">
                                        LE CHAMEAU
                                    </a>

                                </li>


                                <li class="cat-146">
                                    <a href="https://www.outlet46.de/marken-online-outlet/le-coq-sportif-im-outlet/">
                                        Le Coq Sportif
                                    </a>

                                </li>


                                <li class="cat-293">
                                    <a href="https://www.outlet46.de/marken-online-outlet/lee/">
                                        Lee
                                    </a>

                                </li>


                                <li class="cat-577">
                                    <a href="https://www.outlet46.de/marken-online-outlet/lee-cooper/">
                                        Lee Cooper
                                    </a>

                                </li>


                                <li class="cat-147">
                                    <a href="https://www.outlet46.de/marken-online-outlet/levis-im-outlet/">
                                        Levis
                                    </a>

                                </li>


                                <li class="cat-500">
                                    <a href="https://www.outlet46.de/marken-online-outlet/lico/">
                                        LICO
                                    </a>

                                </li>


                                <li class="cat-593">
                                    <a href="https://www.outlet46.de/marken-online-outlet/mammoet/">
                                        MAMMOET
                                    </a>

                                </li>


                                <li class="cat-562">
                                    <a href="https://www.outlet46.de/marken-online-outlet/marc/">
                                        MARC Shoes
                                    </a>

                                </li>


                                <li class="cat-383">
                                    <a href="https://www.outlet46.de/marken-online-outlet/merrell/">
                                        MERRELL
                                    </a>

                                </li>


                                <li class="cat-346">
                                    <a href="https://www.outlet46.de/marken-online-outlet/mizuno-im-outlet/">
                                        Mizuno
                                    </a>

                                </li>


                                <li class="cat-61">
                                    <a href="https://www.outlet46.de/marken-online-outlet/mustang-im-outlet/">
                                        Mustang
                                    </a>

                                </li>


                                <li class="cat-571">
                                    <a href="https://www.outlet46.de/marken-online-outlet/native-shoes/">
                                        native SHOES
                                    </a>

                                </li>


                                <li class="cat-150">
                                    <a href="https://www.outlet46.de/marken-online-outlet/new-balance-im-outlet/">
                                        New Balance
                                    </a>

                                </li>


                                <li class="cat-151">
                                    <a href="https://www.outlet46.de/marken-online-outlet/nike-im-outlet/">
                                        Nike
                                    </a>

                                </li>


                                <li class="cat-529">
                                    <a href="https://www.outlet46.de/marken-online-outlet/penfield/">
                                        PENFIELD
                                    </a>

                                </li>


                                <li class="cat-184">
                                    <a href="https://www.outlet46.de/marken-online-outlet/pierre-cardin/">
                                        Pierre Cardin
                                    </a>

                                </li>


                                <li class="cat-584">
                                    <a href="https://www.outlet46.de/marken-online-outlet/pro-keds/">
                                        PRO-Keds
                                    </a>

                                </li>


                                <li class="cat-613">
                                    <a href="https://www.outlet46.de/marken-online-outlet/prokennex/">
                                        ProKennex
                                    </a>

                                </li>


                                <li class="cat-493">
                                    <a href="https://www.outlet46.de/marken-online-outlet/publish/">
                                        PUBLISH
                                    </a>

                                </li>


                                <li class="cat-160">
                                    <a href="https://www.outlet46.de/marken-online-outlet/puma-im-outlet/">
                                        Puma
                                    </a>

                                </li>


                                <li class="cat-163">
                                    <a href="https://www.outlet46.de/marken-online-outlet/ralph-lauren-im-outlet/">
                                        Ralph Lauren
                                    </a>

                                </li>


                                <li class="cat-563">
                                    <a href="https://www.outlet46.de/marken-online-outlet/ransom/">
                                        RANSOM
                                    </a>

                                </li>


                                <li class="cat-578">
                                    <a href="https://www.outlet46.de/marken-online-outlet/red-tape/">
                                        RED TAPE
                                    </a>

                                </li>


                                <li class="cat-165">
                                    <a href="https://www.outlet46.de/marken-online-outlet/reebok-im-lagerverkauf/">
                                        Reebok
                                    </a>

                                </li>


                                <li class="cat-604">
                                    <a href="https://www.outlet46.de/marken-online-outlet/s-oliver/">
                                        s.Oliver
                                    </a>

                                </li>


                                <li class="cat-585">
                                    <a href="https://www.outlet46.de/marken-online-outlet/salming/">
                                        SALMING
                                    </a>

                                </li>


                                <li class="cat-200">
                                    <a href="https://www.outlet46.de/marken-online-outlet/salomon/">
                                        Salomon
                                    </a>

                                </li>


                                <li class="cat-223">
                                    <a href="https://www.outlet46.de/marken-online-outlet/saucony/">
                                        Saucony
                                    </a>

                                </li>


                                <li class="cat-169">
                                    <a href="https://www.outlet46.de/marken-online-outlet/skechers-im-outlet-im-lagerverkauf/">
                                        Skechers
                                    </a>

                                </li>


                                <li class="cat-170">
                                    <a href="https://www.outlet46.de/marken-online-outlet/slazenger-im-outlet/">
                                        Slazenger
                                    </a>

                                </li>


                                <li class="cat-608">
                                    <a href="https://www.outlet46.de/marken-online-outlet/sorel/">
                                        SOREL
                                    </a>

                                </li>


                                <li class="cat-279">
                                    <a href="https://www.outlet46.de/marken-online-outlet/spartans-history/">
                                        Spartans History
                                    </a>

                                </li>


                                <li class="cat-576">
                                    <a href="https://www.outlet46.de/marken-online-outlet/stance/">
                                        STANCE
                                    </a>

                                </li>


                                <li class="cat-609">
                                    <a href="https://www.outlet46.de/marken-online-outlet/texxor/">
                                        teXXor
                                    </a>

                                </li>


                                <li class="cat-378">
                                    <a href="https://www.outlet46.de/marken-online-outlet/the-north-face/">
                                        The North Face
                                    </a>

                                </li>


                                <li class="cat-174">
                                    <a href="https://www.outlet46.de/marken-online-outlet/timberland-im-outlet/">
                                        Timberland
                                    </a>

                                </li>


                                <li class="cat-176">
                                    <a href="https://www.outlet46.de/marken-online-outlet/tommy-hilfiger-im-outlet/">
                                        Tommy Hilfiger
                                    </a>

                                </li>


                                <li class="cat-340">
                                    <a href="https://www.outlet46.de/marken-online-outlet/u-s-polo-assn-im-outlet/">
                                        U.S. POLO ASSN.
                                    </a>

                                </li>


                                <li class="cat-191">
                                    <a href="https://www.outlet46.de/marken-online-outlet/ugg-australia/">
                                        UGG Australia
                                    </a>

                                </li>


                                <li class="cat-218">
                                    <a href="https://www.outlet46.de/marken-online-outlet/under-armour/">
                                        UNDER ARMOUR
                                    </a>

                                </li>


                                <li class="cat-620">
                                    <a href="https://www.outlet46.de/marken-online-outlet/unze-london/">
                                        Unze London
                                    </a>

                                </li>


                                <li class="cat-607">
                                    <a href="https://www.outlet46.de/marken-online-outlet/us-basic/">
                                        US BASIC
                                    </a>

                                </li>


                                <li class="cat-179">
                                    <a href="https://www.outlet46.de/marken-online-outlet/vans-im-outlet/">
                                        Vans
                                    </a>

                                </li>


                                <li class="cat-247">
                                    <a href="https://www.outlet46.de/marken-online-outlet/wrangler/">
                                        Wrangler
                                    </a>

                                </li>
                                <li class="cat-181">
                                    <a href="https://www.outlet46.de/marken-online-outlet/yellow-cab-im-outlet/">
                                        Yellow Cab
                                    </a>

                                </li>
                                <li class="cat-588">
                                    <a href="https://www.outlet46.de/marken-online-outlet/zapato-europe/">
                                        ZAPATO EUROPE
                                    </a>
                                </li>
                                <li class="cat-182">
                                    <a href="https://www.outlet46.de/marken-online-outlet/zoot-im-outlet/">
                                        Zoot
                                    </a>

                                </li>
                                <li class="cat-332">
                                    <a href="https://www.outlet46.de/marken-online-outlet/sale/">
                                        Flash Sale
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="overlay navigation-overlay closeIcon top-right"
                     data-plenty-toggle="{ target: 'body', class: 'navigation-visible' }"></div>
            </div>
        </div>

    </div>
</nav>

<!--
<header>
    <div class="language-wrapper">
        <div class="language-switch">
            <p><?= $this->__('Please, chose your language') ?></p>

            <a class="lang-flag" href="<?= preg_replace('#[^/]+/?$#', 'de/', $this->getBaseUrl()) ?>">
                <img src="<?= $this->getBaseUrl() ?>images/flags/de.png" alt=""/>
                <span>Deutsch</span>
            </a>
            <a class="lang-flag" href="<?= preg_replace('#[^/]+/?$#', 'en/', $this->getBaseUrl()) ?>">
                <img src="<?= $this->getBaseUrl() ?>images/flags/en.png" alt=""/>
                <span>English</span>
            </a>
            <a class="lang-flag" href="<?= preg_replace('#[^/]+/?$#', 'fr/', $this->getBaseUrl()) ?>">
                <img src="<?= $this->getBaseUrl() ?>images/flags/fr.png" alt=""/>
                <span>Français</span>
            </a>

            <i class="language-switch-close"></i>
        </div>
    </div>

    <div class="header-wrapper clearfix">

        <div id="mobile-menu">
            <span class="lines"></span>
        </div>

        <a href="<?= $this->getBaseUrl() ?>"
           title="<?= $this->__(' - Lizards & Pumpkins') ?>"
           class="logo" >
            <svg class="icon main-logo" viewBox="0 0 1024 1024">
                <use xlink:href="<?= $this->getBaseUrl() ?>images/assets.svg#main-logo"></use>
            </svg>
            <svg class="icon mobile-logo" viewBox="0 0 1024 1024">
                <use xlink:href="<?= $this->getBaseUrl() ?>images/assets.svg#mobile-logo"></use>
            </svg>
        </a>

        <i id="mobile-search">
            <svg class="icon magnifier" viewBox="0 0 1024 1024">
                <use xlink:href="<?= $this->getBaseUrl() ?>images/assets.svg#magnifier"></use>
            </svg>
        </i>

        <ul class="top-links">
            <li id="account-meta"></li>
            <li id="language-switcher">
                <img src="<?= $this->getBaseUrl() ?>images/flags/<?= $currentWebsiteCode ?>.png" alt=""/>
            </li>
            <li>
                <a href="<?= $this->getBaseUrl() ?>checkout/cart/">
                    <svg class="icon-shopping-bag" viewBox="0 0 1024 1024">
                        <use xlink:href="<?= $this->getBaseUrl() ?>images/assets.svg#shopping-bag"></use>
                    </svg>
                    <span id="cart-meta-info"></span>
                </a>
            </li>
        </ul>

        <form id="search_mini_form" action="<?= $this->getBaseUrl() ?>catalogsearch/result/" method="get" autocomplete="off">
            <fieldset>
                <div class="form-search">
                    <input id="search" type="text" name="q"
                           placeholder="<?= $this->__('What are you looking for?') ?>"
                           autocomplete="off" />

                    <button type="submit" title="<?= $this->__('Search') ?>">
                        <svg class="icon magnifier" viewBox="0 0 1024 1024">
                            <use xlink:href="<?= $this->getBaseUrl() ?>images/assets.svg#magnifier"></use>
                        </svg>
                    </button>

                    <div id="search-autosuggestion"></div>
                </div>
            </fieldset>
        </form>
    </div>

    <?= $this->getChildOutput('content_block_main-menu') ?>
</header>-->
