<?php

declare(strict_types=1);

/**
 * @var \LizardsAndPumpkins\Import\TemplateRendering\Block $this
 */
?>
<!--<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
<link rel="icon" href="<?= $this->getBaseUrl() ?>images/favicon.ico" type="image/x-icon" />

<link type="text/css" rel="stylesheet" href="<?= $this->getBaseUrl() ?>css/<?= $this->getLayoutHandle() ?>.css" />

<script data-main="<?= $this->getBaseUrl() ?>js/<?= $this->getLayoutHandle() ?>" src="<?= $this->getBaseUrl() ?>js/lib/require.js"></script>
-->
<head>
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <title>
        <?= $this->getChildOutput('title') ?>
    </title>

    <link rel="canonical" href="https://www.outlet46.de/herren-bekleidung/jeans-hosen/" />
    <link rel="next" href="https://www.outlet46.de/herren-bekleidung/jeans-hosen/?aoff=40" />
    <link rel="stylesheet" type="text/css" href="https://www.outlet46.de/tpl/de/layout/outlet46_ppp/outlet46_ppp_de_content.css?195" />
    <link rel="shortcut icon" type="image/ico" href="https://www.outlet46.de/tpl/favicon_0.ico" />
    <meta name="keywords" content="Timberland Outlet,Damenschuhe,Herrenschuhe,Nike Schuhe,Jeans Outlet" />
    <meta name="description" content="Auf der Suche nach schicken und hochwertigen Herren-Jeans? Entdecken Sie Jeans von Mustang, Cipo &amp; Baxx, Jack &amp; Jones, Wrangler uvm. zu Top-Preisen im Online-Store von Outlet46!" />
    <meta name="robots" content="ALL" />
    <meta name="author" content="Outlet46.de" />
    <meta name="generator" content="lizards and pumpkins" />
    <meta charset="utf-8">
    <style>
        .isLogin,
        .isMyaccount { min-width:120px; }
    </style>
    <script data-main="<?= $this->getBaseUrl() ?>js/<?= $this->getLayoutHandle() ?>" src="<?= $this->getBaseUrl() ?>js/lib/require.js"></script>
    <link type="text/css" rel="stylesheet" href="<?= $this->getBaseUrl() ?>css/<?= $this->getLayoutHandle() ?>.css" />
</head>
{{snippet head_container}}