<?php

declare(strict_types=1);

/**
 * @var \LizardsAndPumpkins\Import\TemplateRendering\Block $this
 */
?>
<!DOCTYPE html>
<html>
    <?= $this->getChildOutput('head') ?>
<body class="js plenty de isCat-36 filterExist isFacets size-lg">
<div class="wrapper">
    <a id="top"></a>
    <?= $this->getChildOutput('header') ?>
    <div id="content" class="two-cols clearfix">
        <div class="side-bar col span_2">
            <?= $this->getChildOutput('left') ?>
        </div>
        <div class="page-content col span_10 container">
            <?= $this->getChildOutput('content') ?>
        </div>
    </div>
    <?= $this->getChildOutput('footer') ?>
</div>
</body>
</html>
